// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaylzuVZjA-53Ge3qayoTZ9QoQe8OWStQ',
    appId: '1:749036237783:web:88ec12f65feae5bc055192',
    messagingSenderId: '749036237783',
    projectId: 'sharp-stack-383904',
    authDomain: 'sharp-stack-383904.firebaseapp.com',
    storageBucket: 'sharp-stack-383904.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA82MXzEEJFYBnzPSl4CnMyjQKVTVNGWEg',
    appId: '1:749036237783:android:e3548208d20b13e6055192',
    messagingSenderId: '749036237783',
    projectId: 'sharp-stack-383904',
    storageBucket: 'sharp-stack-383904.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA4l6lwIQ-Q9CNDw6H8QzkDovkICG2hWI',
    appId: '1:749036237783:ios:156e00cb0f254412055192',
    messagingSenderId: '749036237783',
    projectId: 'sharp-stack-383904',
    storageBucket: 'sharp-stack-383904.appspot.com',
    iosClientId: '749036237783-632sa26l7vmmtrd5icetj2lqs0b8inn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.rideSharing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA4l6lwIQ-Q9CNDw6H8QzkDovkICG2hWI',
    appId: '1:749036237783:ios:52b6846b5633b8a5055192',
    messagingSenderId: '749036237783',
    projectId: 'sharp-stack-383904',
    storageBucket: 'sharp-stack-383904.appspot.com',
    iosClientId: '749036237783-ahe07ekth2n3g1agr3lkhut8vnvitk86.apps.googleusercontent.com',
    iosBundleId: 'com.example.rideSharing.RunnerTests',
  );
}
